on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: |
        dotnet new console
        dotnet pack

    - uses: jcansdale/gpr@0.1.255-gb0eaba2381
      with:
        command: push
        path: "**/*.nupkg"
        args: "--repository ${{ github.repository }} --version 1.0.0-g${{ github.sha }}"

    - uses: jcansdale/gpr@action
      with:
        command: list
        path: ${{ github.repository }}

    - uses: jcansdale/gpr@action
      with:
        command: delete
        path: ${{ github.repository }}
        args: "--version 1.0.0"
