on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: jcansdale/gpr@action
      with:
        path: ${{ github.repository_owner }}
