on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: |
        dotnet new console
        dotnet pack

    - uses: jcansdale/gpr@action
      with:
        command: push
        path: "**/*.nupkg"
        options: --repository ${{ github.repository }}

    - uses: jcansdale/gpr@action
      with:
        command: list
        path: ${{ github.repository }}
